ruby_on_rails/blog2/config/routes.rb
Rails.application.routes.draw do
  #get 'sessions/new'
  resources :sessions, only: [:new, :create, :destroy]

  # get 'users/new'
  resources :users, only: [:new, :create]

  # get 'contacts/index'
  # get 'contacts/new'
  # post 'contacts/create'
  resources :contacts, only: [:index, :create, :new]

  get '/' => 'home#hello_world'
  get '/index' => 'home#index'
  get '/contact' => 'home#contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

ruby_on_rails/blog2/app/models/contact.rb
class Contact < ApplicationRecord
end

ruby_on_rails/blog2/app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

ruby_on_rails/blog2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include SessionsHelper

    def authenticate
        redirect_to new_session_path unless user_signed_in?
    end

    def authenticate_admin
        
        unless current_user.admin
            flash[:alert] = 'no admin'
            redirect_to '/'
        end
    end
end

ruby_on_rails/blog2/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate, only: [:index]
  before_action :authenticate_admin, only: [:index]

  def index
    @all_contacts = Contact.all
  end

  def new

  end

  def create
    @name = params[:name]
    @email = params[:email]
    @content = params[:content]

    # db저장
    new_contact = Contact.new(name: @name, email: @email, content: @content)
    if(new_contact.save)
      # redirect_to "/contacts/index"
      redirect_to contacts_path
    else
      # redirect_to "/contacts/new"
      redirect_to new_contact_path
    end
  end
end

ruby_on_rails/blog2/app/controllers/home_controller.rb
class HomeController < ApplicationController
    def hello_world
        # render 'render_page'
    end

    def index
    end
    
    def contect
    end
end

ruby_on_rails/blog2/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      # session[:user_id] = user.id
      log_in(user)
      redirect_to '/'
    else
      flash[:alert] = 'Invalid email/password combination'
      redirect_to new_session_path
    end
  end

  def destroy
    log_out
    redirect_to '/'
  end

end

ruby_on_rails/blog2/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    User.create(
      email: params[:email],
      password: params[:password],
      password_confirmation: params[:password_confirmation],
      name: params[:name]
    )
    redirect_to '/'
  end
end

ruby_on_rails/blog2/app/helpers/contacts_helper.rb
module ContactsHelper
end

ruby_on_rails/blog2/app/helpers/home_helper.rb
module HomeHelper
end

ruby_on_rails/blog2/app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end

    def current_user
        # if @current_user.nil?
        #     @current_user = User.find_by(id: session[:user_id])
        # end
        # return @current_user


        # @current_user = @current_user || User.find_by(id: session[:user_id])
        # return @current_user

        @current_user ||= User.find_by(id: session[:user_id])
        return @current_user
    end

    def user_signed_in?
        !current_user.nil?
    end

    def log_out
        session.delete(:user_id)
        # session[:user_id] = nil
        @current_user = nil
    end
end

ruby_on_rails/blog2/app/helpers/users_helper.rb
module UsersHelper
end

ruby_on_rails/blog2/app/views/contacts/create.html.erb
<h1>Contacts#create</h1>
<p>Find me in app/views/contacts/create.html.erb</p>

<%= @name%>
<br>
<%= @email%>
<br>
<%= @content%>

ruby_on_rails/blog2/app/views/contacts/index.html.erb
<h1>All Contacts</h1>
<ul>
    <% @all_contacts.each do |con| %>
        <li><%= con.name %> : <%= con.content%> : <%= con.email%></li>
    <% end %>
</ul>

ruby_on_rails/blog2/app/views/contacts/new.html.erb
<%# get %>
<%# <form action="/contacts/create" method="get">
    Name : <input type="text" name="name">
    <br>
    Email : <input type="email" name="email">
    <br>
    Content : <textarea name="content" id="" cols="30" rows="10"></textarea>
    <br>
    <input type="submit">
</form> %>



<%# post %>
<%# <%= form_tag "/contacts/create" do %> %>
    <%# Name : <input type="text" name="name">
    <br>
    Email : <input type="email" name="email">
    <br>
    Content : <textarea name="content" id="" cols="30" rows="10"></textarea>
    <br>
    <input type="submit"> %>
<%# <% end %> %>

<%# 라우팅 후 %>
<%= form_tag contacts_path do %>
    Name : <input type="text" name="name">
    <br>
    Email : <input type="email" name="email">
    <br>
    Content : <textarea name="content" id="" cols="30" rows="10"></textarea>
    <br>
    <input type="submit">
<% end %>

ruby_on_rails/blog2/app/views/home/contact.html.erb
<h1>Contact Page</h1>

<%# 이미지넣기 %>
<%= image_tag("nayen.jpg") %>

ruby_on_rails/blog2/app/views/home/index.html.erb
<h1>this is menu</h1>
<%= render partial: "shared/menu", locals: {title:"Menu1"} %>
<%= render partial: "shared/menu", locals: {title:"Menu2"} %>

<div>
    2 * 2 = <strong><%= 2 * 2 %></strong>
    <br>
    2 * 3 = <strong><%= 'hi' %></strong>
</div>

<% if 1+1 == 2 %>
    <span>Correct!</span>
<% else %>
    <span>Wrong!</span>
<%end%>

<% ['aa', 'bb', 'cc', 'dd'].each do |name| %>
    <span><%= name %></span>
<% end %>

<h1>현재시간</h1>
<span><%= DateTime.now %></span>

ruby_on_rails/blog2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="global-header">
      <div class="container">
        <div class="logo">
          My Profile
        </div>
        <ul class="menu">
          <a href="/">
            <li class="item">HOME</li>
          </a>
          <%# <a href="/contact"> %>
          <%# <a href="/contacts/new"> %>
          <%= link_to new_contact_path do %>
            <li class="item">Contact</li>
          <% end %>
          <% if user_signed_in? %>
            <li class="item"><%= current_user.name %></li>
            <li class="item"><%= link_to 'Sign out', session_path(current_user), method: 'delete' %></li>
            <% if current_user.admin %>
              <li class="item"><%= link_to 'Contacts List', contacts_path %></li>
            <% end %>
          <% else %>
            <li class="item"><%= link_to 'Sign in', new_session_path %></li>
            <%= link_to new_user_path do %>
              <li class="item"><%= link_to 'Sign up', new_user_path %></li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
    <div id="wrapper">
      <%= flash[:alert] %>
      <%= yield %>
    </div>
  </body>
</html>

ruby_on_rails/blog2/app/views/shared/_menu.html.erb
<p>shared menu : <%= title %></p>


ruby_on_rails/blog2/app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_tag users_path do %>
    Email : 
    <input type="email" name="email">
    <br>

    Password :
    <input type="password" name="password">
    <br>

    Password Confirmation : 
    <input type="password" name="password_confirmation">
    <br>

    Name : 
    <input type="text" name="name">
    <br>

    <input type="submit" value="Sign up">
<% end %>